---
version: "3.1"
services:
  db:
    image: postgres
    container_name: postgres-sql
    restart: always
    environment:
      - POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - $ADMINER_PORT:8080
  
